// scripts/generateQuizComponentList.js
const fs = require('fs');
const path = require('path');
const { randomUUID } = require('crypto');

function getMarkdownFiles(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  return entries.flatMap((entry) => {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      return getMarkdownFiles(fullPath);
    }
    if (entry.isFile() && (fullPath.endsWith('.md') || fullPath.endsWith('.mdx'))) {
      return [fullPath];
    }
    return [];
  });
}


function extractComponentProps(content, componentName) {
  const tagRegex = new RegExp(`<${componentName}(\\s+[^>]*?)?>`, 'gi');
  const components = [];

  let match;
  while ((match = tagRegex.exec(content)) !== null) {
    const propsString = match[1] || '';

    const nameMatch = /name\s*=\s*["']([^"']+)["']/i.exec(propsString);

    if (nameMatch) {
      components.push({
        name: nameMatch[1],
      });
    }
  }

  return components;
}


function findComponentUsage(rootDir, componentName) {
  const files = getMarkdownFiles(rootDir);
  const cwd = process.cwd();

  const results = [];

  for (const file of files) {
    const content = fs.readFileSync(file, 'utf-8');
    const matches = extractComponentProps(content, componentName);

    // Remove file ending
    const page = path.relative(cwd, file).split(".")[0];

    matches.forEach((match) => {
      let id = page.replace("docs/", "") + "#" + match.name.replace(" ", "+");

      // Remove numbers followed by an underscore (e.g., '03_' becomes '')
      id = id.replace(/\b\d+_/g, "");

      id = id.toLocaleLowerCase();
      results.push({
        page: page,
        name: match.name,
        id: id,
      });
    });
  }

  return results;
}


function writeComponentListToFile(components, outputFilePath) {
  const date = new Date().toLocaleString();
  const header = `/*
* This file is automatically generated and will be overridden when running the build process.
* Generated on: ${date}
*/

export interface QuizComponent {
  id: string | null;
  page: string;
  name: string;
}

export const quizComponents: QuizComponent[] = [\n`;

  const items = components.map(
    ({ page, name, id }) =>
      `  {
    page: '${page}',
    name: '${name}',
    id: '${id}',
  }`
  );

  const footer = `\n];\n`;

  const fullContent = header + items.join(',\n') + footer;
  fs.writeFileSync(outputFilePath, fullContent, 'utf-8');
  console.log(`Generated ${outputFilePath} with ${components.length} components.`);
}

const componentName = 'Quiz';
const rootDir = path.resolve(process.cwd(), 'docs');
const outputFilePath = path.resolve(process.cwd(), 'src/components/Quiz/quizComponents.ts');

const quizComponents = findComponentUsage(rootDir, componentName);
writeComponentListToFile(quizComponents, outputFilePath);
