/*
* This file is automatically generated and will be overridden when running the build process.
* Generated on: 6/4/2025, 7:22:20 AM
*/

export interface QuizPage {
  id: string;
  name: string;
  quizzes: QuizComponent[];
}

export interface QuizComponent {
  id: string | null;
  name: string;
}

export const quizPages: QuizPage[] = [
  {
    "id": "docs-chapter-02-03_executing",
    "name": "executing",
    "quizzes": [
      {
        "id": "chapter-02/executing#executing+rf",
        "name": "Executing RF"
      }
    ]
  },
  {
    "id": "docs-example-exam-Example-exam",
    "name": "Example-exam",
    "quizzes": [
      {
        "id": "example-exam/example-exam#example1",
        "name": "example1"
      }
    ]
  },
    {
    "id": "docs-example-exam-Example-exam2",
    "name": "Example-exam",
    "quizzes": [
      {
        "id": "example-exam/example-exam#example12",
        "name": "example1"
      }
    ]
  },  {
    "id": "docs-example-exam-Example-exam3",
    "name": "Example-exam",
    "quizzes": [
      {
        "id": "example-exam/example-exam#example13",
        "name": "example1"
      }
    ]
  }
  ,  {
    "id": "docs-example-exam-Example-exam4",
    "name": "Example-exam",
    "quizzes": [
      {
        "id": "example-exam/example-exam#example14",
        "name": "example1"
      }
    ]
  }
];
