/*
* This file is automatically generated and will be overridden when running the build process.
* Generated on: 7/17/2025, 11:44:41 AM
*/

export interface QuizPage {
  id: string;
  name: string;
  quizzes: QuizComponent[];
}

export interface QuizComponent {
  id: string | null;
  name: string;
}

export const quizPages: QuizPage[] = [
  {
    "id": "docs-chapter-02-03_executing",
    "name": "executing",
    "quizzes": [
      {
        "id": "chapter-02/executing#executing+rf",
        "name": "Executing RF"
      }
    ]
  },
  {
    "id": "docs-example-exam",
    "name": "example-exam",
    "quizzes": [
      {
        "id": "example-exam#example1",
        "name": "example1"
      }
    ]
  }
];
